In [1]:
!pip install torch torchvision torchaudio


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 3.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 32.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 37.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 40.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 13.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 6.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 78.6 MB/s eta 0:00:00
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlin

In [2]:
import torch
import torch.nn as nn  # Module for creating neural networks
import torch.optim as optim  # Optimizers for training
import torch.nn.functional as F  # Activation functions


In [3]:
# Creating a tensor from a list
x = torch.tensor([1, 2, 3])
print(x)

# Creating a 2D tensor (matrix)
y = torch.tensor([[1, 2], [3, 4]])
print(y)

# Creating a tensor with random values
random_tensor = torch.rand(3, 3)  # 3x3 matrix with random values
print(random_tensor)

# Creating a tensor with zeros
zero_tensor = torch.zeros(2, 2)
print(zero_tensor)

# Creating a tensor with ones
ones_tensor = torch.ones(2, 3)
print(ones_tensor)


tensor([1, 2, 3])
tensor([[1, 2],
        [3, 4]])
tensor([[0.3283, 0.3278, 0.0175],
        [0.2974, 0.4607, 0.6243],
        [0.0931, 0.3388, 0.7590]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [4]:
print(f"Shape: {x.shape}")  # Shape of the tensor
print(f"Data type: {x.dtype}")  # Data type
print(f"Device: {x.device}")  # Device where tensor is stored


Shape: torch.Size([3])
Data type: torch.int64
Device: cpu


In [5]:
a = torch.tensor([3, 4, 5])
b = torch.tensor([1, 2, 3])

# Addition
c = a + b
print(c)  # Output: tensor([4, 6, 8])

# Subtraction
d = a - b
print(d)  # Output: tensor([2, 2, 2])

# Multiplication
e = a * b
print(e)  # Output: tensor([3, 8, 15])

# Matrix multiplication (dot product)
A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[5, 6], [7, 8]])
C = torch.matmul(A, B)
print(C)  # Matrix multiplication result


tensor([4, 6, 8])
tensor([2, 2, 2])
tensor([ 3,  8, 15])
tensor([[19, 22],
        [43, 50]])


In [6]:
device = "cuda" if torch.cuda.is_available() else "cpu"
tensor = torch.tensor([1, 2, 3], device=device)
print(tensor)


tensor([1, 2, 3])


In [7]:
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(5, 10)  # Input layer (5 features) → 10 neurons
        self.fc2 = nn.Linear(10, 1)  # Hidden layer → Output layer (1 neuron)

    def forward(self, x):
        x = F.relu(self.fc1(x))  # Activation function
        x = torch.sigmoid(self.fc2(x))  # Output layer with sigmoid activation
        return x


In [8]:
model = SimpleNN()
print(model)


SimpleNN(
  (fc1): Linear(in_features=5, out_features=10, bias=True)
  (fc2): Linear(in_features=10, out_features=1, bias=True)
)


In [9]:
loss_fn = nn.BCELoss()  # Binary Cross Entropy for binary classification
optimizer = optim.Adam(model.parameters(), lr=0.001)  # Adam optimizer


In [10]:
# Dummy training data
X_train = torch.rand(100, 5)  # 100 samples, 5 features
y_train = torch.randint(0, 2, (100, 1)).float()  # 100 binary labels

epochs = 10  # Number of training loops

for epoch in range(epochs):
    optimizer.zero_grad()  # Reset gradients
    outputs = model(X_train)  # Forward pass
    loss = loss_fn(outputs, y_train)  # Compute loss
    loss.backward()  # Backpropagation
    optimizer.step()  # Update weights

    print(f"Epoch {epoch+1}, Loss: {loss.item():.4f}")


Epoch 1, Loss: 0.6893
Epoch 2, Loss: 0.6890
Epoch 3, Loss: 0.6888
Epoch 4, Loss: 0.6885
Epoch 5, Loss: 0.6883
Epoch 6, Loss: 0.6880
Epoch 7, Loss: 0.6878
Epoch 8, Loss: 0.6875
Epoch 9, Loss: 0.6873
Epoch 10, Loss: 0.6871


In [11]:
X_test = torch.rand(5, 5)  # 5 test samples, 5 features
predictions = model(X_test)
print(predictions)  # Outputs probability scores


tensor([[0.4929],
        [0.5306],
        [0.4999],
        [0.5088],
        [0.5141]], grad_fn=<SigmoidBackward0>)


In [12]:
torch.save(model.state_dict(), "model.pth")  # Save model parameters


In [13]:
model = SimpleNN()  # Re-initialize the model
model.load_state_dict(torch.load("model.pth"))  # Load saved weights
model.eval()  # Set to evaluation mode


<ipython-input-13-85a64eeb2d2f>:2: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load("model.pth"))  # Load saved weights


SimpleNN(
  (fc1): Linear(in_features=5, out_features=10, bias=True)
  (fc2): Linear(in_features=10, out_features=1, bias=True)
)